spring:
  datasource:
    url: jdbc:mysql://14.225.215.99:3306/koi-vet-db
    username: anhtu
    password: 489364Glte@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


openapi:
  service:
    api-docs: Koi-Vetenarian-Service API
    server: http://localhost:8080
    title: Koi-Vetenarian-Service API
    version: 1.0.0
springdoc:
  swagger-ui:
    enabled: true
